#!/usr/bin/env python3

"""
edit

usage: mango @edit [script_name]

This is a prebuilt script in the builtins submodule.
It is shipped with mango and is automatically installed in the user's home mango.

The script is called to edit a script in the current directory. If the script does not exist,
an error will be raised.
"""

import argparse
import os

from _common import closestMangoRepo, openInEditor
from _cprint import fatal_error


def edit():
    """Edit a script in the current directory."""
    parser = argparse.ArgumentParser(description='Edit a script in the current directory.')
    parser.add_argument('script_name', type=str, help='The name of the script to edit.')
    args = parser.parse_args()

    script_name = args.script_name
    
    try:
        repo_path = closestMangoRepo(os.getcwd())
    except FileNotFoundError:
        fatal_error("No mango repository found.")
        
    script_path = os.path.join(repo_path, '.mango', script_name)

    if not os.path.exists(script_path):
        fatal_error(f"'{script_name}' does not exist in mango repository {repo_path}! Maybe call @add to create it?")

    # Get the default editor from environment variable or use nano
    default_editor = os.environ.get('EDITOR', 'nano')
    openInEditor(default_editor, script_path)


if __name__ == '__main__':
    edit()
